### ISSUE TITLE
Gas Price Oracle library usage

### ISSUE THREAD

**Issue by akolotov** [xdaichain/omnibridge#148]
Consider to use the gas price oralce library (https://github.com/peppersec/gas-price-oracle) instead of the Gas Price Oracle URL since it is more robust in case when the oracle URL is not available.

**Comment by dan13ram** [comment]
@akolotov we were already using this library, and the code still exists in https://github.com/xdaichain/omnibridge/blob/master/packages/react-app/src/lib/gasPrice.js.

But setting the gasPrice in our ethersProvider led to some errors as discussed in this issue https://github.com/ethers-io/ethers.js/issues/1232. Therefore, for the time being we have removed the use of this library and are letting the user's wallet decide the gasPrice.

**Comment by akolotov** [comment]
> But setting the gasPrice in our ethersProvider led to some errors as discussed in this issue [ethers-io/ethers.js#1232](https://github.com/ethers-io/ethers.js/issues/1232). Therefore, for the time being we have removed the use of this library and are letting the user's wallet decide the gasPrice.

@dan13ram thanks for updates. But from my understanding the gas price oracle is still used to provide the gas estimation when a user requests a token transfer from the xDai chain. Am i right?

**Comment by dan13ram** [comment]
Not currently. It is left to the user's wallet to decide the gas price even for xDai network. 
We only use the oracle to show tentative tx costs in the confirmation modal.

**Comment by akolotov** [comment]
Correct. I said exactly about this confirmation modal. Does it use the gas price oracle library?

**Comment by dan13ram** [comment]
Yes it does :)

>
