### ISSUE TITLE
History tab does not reflect a transfer made with the alternative receiver feature

### ISSUE THREAD

**Issue by akolotov** [xdaichain/omnibridge#149]
If a user A transfers a token and specifies an address B in the recipient address field the user B do not see this transfer on the history tab (therefore they cannot claim it).

Consider to implement the logic as so both the user A and the user B will be able to see  in the history tab the transfers sent by using the alternative receiver feature. If some transfer is not finilized yet both users will need to have an ability to press the 'Claim' button.

**Comment by dan13ram** [comment]
@akolotov are there any events that log the receiver address? 
If not what is the best way to ascertain the receiver address for a given transaction or messageId ?

**Comment by akolotov** [comment]
Here is an example of the transfer:

https://blockscout.com/xdai/mainnet/tx/0x014764008af1c2f87c387fb07b8afefd2d6fd30746738aa614a6588029066efb/logs

The only way to get the receiver address is to extract it from the content of the `encodedData` field of the event `UserRequestForSignature` (`UserRequestForSignature` for the messages from the Ethereum Mainnet):
```
                       1                   2                   3
   0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
0x00050000a7823d6f1e31569f51861e345b30c6bebf70ebe7000000000000292d

                   4                   5                   6
   2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3
  f6a78083ca3e2a662d6dd1703c939c8ace2e268d88ad09518695c6c3712ac10a

               7                   8                   9
   4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5
  214be5109a65567100061a800101806401125e4cfb0000000000000000000000
  000ae055097c6d159879521c384f1d2123d1f195e60000000000000000000000
  00e4c2820ec69410907f312b7487af3dfb32640c330000000000000000000000
  000000000000000000000000000ddd2935029d8000
```
In this message the sender is receiver `0xe4c2820ec69410907f312b7487af3dfb32640c33`.

The first bytes in the encodedData are the AMB message header: https://github.com/poanetwork/tokenbridge-contracts/blob/cdef2c6d696e46677a9125a064ab6c8c514bfc9d/contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol#L85

The length of the header is `(79 + header[76] + header[77])`

The rest of the bytes is the encoded call of one of the following methods:
  * `handleBridgedTokens`
  * `handleBridgedTokensAndCall`
  * `deployAndHandleBridgedTokens`
  * `deployAndHandleBridgedTokensAndCall `
  * `handleNativeTokens`
  * `handleNativeTokensAndCall`

Here is the contract's code preparing the call: https://github.com/poanetwork/omnibridge/blob/51e57e53150ae8a54ce9653a92e8440407af8c90/contracts/upgradeable_contracts/BasicOmnibridge.sol#L315. 

The ABI of these methods are available in the [BasicOmnibridge](https://github.com/poanetwork/omnibridge/blob/develop/contracts/upgradeable_contracts/BasicOmnibridge.sol) module.
