### ISSUE TITLE
Simplify the token management by an "Add to MetaMask" button 

### ISSUE THREAD

**Issue by akolotov** [xdaichain/omnibridge#153]
Lots of users are struggling with finding bridged tokens in their wallet since the MetaMask does not discover the tokens in sidechains automatically. 

Consider to add the button "Add to MetaMask" (https://docs.metamask.io/guide/registering-your-token.html) in the part of the window where the bridged token is displayed and in the history tab.

![image](https://user-images.githubusercontent.com/20793260/109705834-d6bfc880-7b5d-11eb-992e-789213d78976.png)

**Comment by akolotov** [comment]
> Perhaps we can add it to the left-side (fromToken) side.

It does not look logical. The left side for the tokens I own. May we have a modal window which will appear when the user presses the fox icon on the right side? The modal will ask the user to switch to the proper chain and then press a button to add the token.  Does it make sense?

**Comment by dan13ram** [comment]
Sure that does make sense. I'll see what I can do
