### ISSUE TITLE
"Add to the xDai chain to MetaMask" button to simplify onboarding

### ISSUE THREAD

**Issue by akolotov** [xdaichain/omnibridge#158]
Recently [MetaMask started supporting](https://consensys.net/blog/metamask/connect-users-to-layer-2-networks-with-the-metamask-custom-networks-api/) [EIP-3085](https://eips.ethereum.org/EIPS/eip-3085). So, it makes sense to add a button like "Add the xDai chain to MetaMask" to the following window:

![image](https://user-images.githubusercontent.com/20793260/109885141-a6525a00-7c43-11eb-8832-5d9fa747dfb5.png)

[Here](https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods) is more details about an API call which should be used to implement this.

**Comment by sunguru98** [comment]
#177 and #181 solves this issue. Hence closing it.

**Comment by akolotov** [comment]
@dan13ram @sunguru98 

I think it is not clear for the end user which action it must do to add the chain:

![image](https://user-images.githubusercontent.com/20793260/111518422-abbba400-871b-11eb-9be2-1fe96f692caf.png)

1. It is not evident that I need to move the cursor to the blue tile

![image](https://user-images.githubusercontent.com/20793260/111518565-cbeb6300-871b-11eb-95a6-43984287890c.png)

2. Even if I discover this, it is not cleared that I need to press on it.

3. It is not evident that pressing on this tile will add the chain into the wallt.

**Comment by akolotov** [comment]
Would it be one of the simplest solutions to add a fox icon within the tile?

**Comment by dan13ram** [comment]
> Would it be one of the simplest solutions to add a fox icon within the tile?

Great idea @akolotov . Lets do it. Do you think it makes sense to also change the tooltip text to 'Click to switch to xDai chain' ?

**Comment by sunguru98** [comment]
I'll take both of your suggestions and create a PR for the same :)
