### ISSUE TITLE
Get fees from the FeesManager 

### ISSUE THREAD

**Issue by akolotov** [xdaichain/omnibridge#165]
Due to bytecode size limit in the new version of OB contracts the functionality to keep and calculate fees for specific tokens is moved to a separate contract [`FeeManager`](https://github.com/poanetwork/omnibridge/blob/master/contracts/upgradeable_contracts/modules/fee_manager/OmnibridgeFeeManager.sol). 

It means that the methods `HOME_TO_FOREIGN_FEE`, `FOREIGN_TO_HOME_FEE`, `calculateFee` and `isRewardAddress` are not available in the OB mediator contract anymore.

In order to use these methods, the OB fee manager contract address must be get from the mediator contract ([`feeManager()`](https://github.com/poanetwork/omnibridge/blob/ea0ffa6f015da024306d80f61bd271c4268b1f7a/contracts/upgradeable_contracts/modules/fee_manager/OmnibridgeFeeManagerConnector.sol#L33)) first. After that the methods listed above can be requested from the fee manager contract.

**Comment by alexkeating** [comment]
This issue should be resolved now with pr #198

**Comment by akolotov** [comment]
@dan13ram @alexkeating this changes broke the existing functionality on the ETH-xDAI bridge.

![image](https://user-images.githubusercontent.com/20793260/113695962-af917500-968e-11eb-89f9-6c6874bf6434.png)

You need to distinguish which contracts you are working on and extract the fees properly on the previous version of the contracts.

**Comment by dan13ram** [comment]
@akolotov I've reverted the changes until we fix this cleanly. 

> You need to distinguish which contracts you are working on and extract the fees properly on the previous version of the contracts.
What is the best way you suggest we do this?
Would it be as simple as reverting to the old way of fetching fees for the mainnet-xdai mediator on xdai [0xf6A78083ca3e2a662D6dd1703c939c8aCE2e268d](https://blockscout.com/poa/xdai/address/0xf6A78083ca3e2a662D6dd1703c939c8aCE2e268d/read-proxy) ?

**Comment by akolotov** [comment]
> What is the best way you suggest we do this?
> Would it be as simple as reverting to the old way of fetching fees for the mainnet-xdai mediator on xdai [0xf6A78083ca3e2a662D6dd1703c939c8aCE2e268d](https://blockscout.com/poa/xdai/address/0xf6A78083ca3e2a662D6dd1703c939c8aCE2e268d/read-proxy) ?

I would suggest to use [the method `getBridgeInterfacesVersion()`](https://github.com/poanetwork/omnibridge/blob/ea0ffa6f015da024306d80f61bd271c4268b1f7a/contracts/upgradeable_contracts/components/common/OmnibridgeInfo.sol#L34) to discover if the contracts support the fee manager as a separate contract. If the version is `2.1.0` and higher it is necessary to get the address of the fee manager from the OB contract and get data from the manager. If the version is lower than `2.1.0` the fees data can be requested from the OB contract itself.
