### ISSUE TITLE
Support of bridging native tokens to ERC677 tokens

### ISSUE THREAD

**Issue by akolotov** [xdaichain/omnibridge#166]
Recently the OB contracts were updated with a new feature "relay-and-call" which allows to implement new scenarios on the OmniBridge:
  * https://github.com/poanetwork/omnibridge/blob/master/contracts/helpers/README.md
  * https://docs.tokenbridge.net/bsc-xdai-amb/omnibridge-extension/transfer-wbnb-on-xdai-to-bnb-on-bsc

Consider to support of transferring native tokens (ETH, BNB) from the Foreign side of bridge in form of ERC677 tokens to the xDai chain and vice versa.:
  1. A user should have an ability to send both native and wrapped tokens through the bridge.
  2. A user should have an ability to specify which tokens (native or wrapped) he/she would like to receive after sending the ERC677 version of ETH/BNB to the bridge.

For testing on the Kovan-Sokol bridge the following helper contract can be used: https://kovan.etherscan.io/address/0x227a6f13aa0dba8912d740c0f88fb1304b2597e1#code.

**Comment by dan13ram** [comment]
@akolotov can you confirm the helper contract address for ETH on Mainnet?
got the BNB contract from the docs: 0xefc33f8b2c4d51005585962be7ea20518ea9fd0d
and Kovan you've mentioned above: 0x227a6f13aa0dba8912d740c0f88fb1304b2597e1

**Comment by akolotov** [comment]
> @akolotov can you confirm the helper contract address for ETH on Mainnet?
> got the BNB contract from the docs: 0xefc33f8b2c4d51005585962be7ea20518ea9fd0d
> and Kovan you've mentioned above: 0x227a6f13aa0dba8912d740c0f88fb1304b2597e1

@dan13ram There is no helper contract for the Ethereum Mainnet yet since the method `relayTokensAndCall` is supported only in the new version of contracts which is still on the audit and that is why it is not deployed yet for the ET-xDAI bridge.

**Comment by dan13ram** [comment]
Thanks @akolotov.

**Comment by dan13ram** [comment]
Closed by #211
