### ISSUE TITLE
Issue with sending more then one token from XDAI Mainnet to ETH Mainnet (Aave, Unisocks vs. WBTC, TBTC)

### ISSUE THREAD

**Issue by jyakov** [xdaichain/omnibridge#172]
It seems that there is a limit on sending certain tokens and that they need to have the value of at least 1 token, even though the token price can be very high, such as (Aave, Unisocks vs. WBTC, TBTC). Is there anyway the minimum could be lowered for tokens like Aave and Socks.

**Comment by akolotov** [comment]
> It seems that there is a limit on sending certain tokens and that they need to have the value of at least 1 token, even though the token price can be very high, such as (Aave, Unisocks vs. WBTC, TBTC). Is there anyway the minimum could be lowered for tokens like Aave and Socks.

Can you double check this? The lower limit for the bridge transfer was reduced recently.

**Comment by jyakov** [comment]
It is good now, I was able to send Unisocks back and forth, thank you!
