### ISSUE TITLE
Amount of available tokens multiplied by 1,000,000,000

### ISSUE THREAD

**Issue by dysbulic** [xdaichain/omnibridge#173]
When I view the xDai currency selection screen, the number of available tokens is wildly inflated:

<img src="https://user-images.githubusercontent.com/181523/111020888-f42f3680-8396-11eb-8fa2-75f3a732fb9f.png" width="250"/>

When I select xSEED, however, it populates the `max` field with the right amount (2.57). The amount of tokens to unlock is off though:

<img src="https://user-images.githubusercontent.com/181523/111020921-20e34e00-8397-11eb-974b-cc6a2f01ed39.png" width="250"/>

**Comment by dan13ram** [comment]
Thanks for reporting this issue @dysbulic 

We use the token-list at http://tokens.honeyswap.org/ for fetching the default token details on xDai.
They seem to have incorrectly set the xSEED token decimals as 9. I've raised an issue for the same. 
Please follow the following issue to ensure it is fixed =)

https://github.com/1Hive/default-token-list/issues/74

**Comment by dan13ram** [comment]
This issue has been fixed and deployed by 1hive team.
